channels:
  - conda-forge
dependencies:
  - python=3.12.2
  - pip<=25.0.1
  - pip:
      - mlflow==2.19.0
      - cloudpickle==3.1.1
      - numpy==1.26.4
      - pandas==2.2.3
      - psutil==6.1.0
      - scikit-learn==1.6.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - imbalanced-learn==0.13.0
name: mlflow-env
